# Configuration for robvanderleek/create-issue-branch

# Create the branch immediately when the workflow invokes the action.
mode: immediate

# Default branch name if no component label matches.
branchName: 'issue-${issue.number}-${issue.title}'

# Select the branch name based on the component label.
branches:
  - label: 'database'
    prefix: 'iteration-1-database/'

  - label: 'backend'
    prefix: 'iteration-2-backend/'

  - label: 'frontend'
    prefix: 'iteration-3-frontend/'

# Normalize generated branch names.
branchNameTransformations:
  - lower-case
  - replace-spaces-with-hyphens
